### ISSUE TITLE
I am getting Error when I run the code

### ISSUE THREAD

**Issue by ustunsoz** [ductsoup/TentacleT3-ModbusTK-Example#1]
The following Error occurs when I run the code, how can I handle it?

```
pi@garden:~/atlasi2c $ python3 main.py
Ready
server error: [Errno 13] Permission denied
40001  QC: 3.141593
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    rtd = ezo.read_rtd()
  File "main.py", line 62, in read_rtd
    return float((self.query("R").split(" ")[2]).rstrip('\0'))
ValueError: could not convert string to float: '102:'
```

**Comment by ductsoup** [comment]
Try running as root or using sudo in front of the command. Access to ports under 1024 require root permission and you're probably using the default 502.

**Comment by ustunsoz** [comment]
Thanks for the reply. 
When I run with sudo the value error still persist :
```
pi@garden:~/atlasi2c $ sudo python3 main.py
Ready
40001  QC: 3.141593
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    rtd = ezo.read_rtd()
  File "main.py", line 62, in read_rtd
    return float((self.query("R").split(" ")[2]).rstrip('\0'))
ValueError: could not convert string to float: '102:'
```
My device addresses are as follow, should I change any address in AtlasI2c.py?
```
pi@garden:~/atlasi2c $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- 63 64 -- 66 -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

```

**Comment by ductsoup** [comment]
Addresses look fine but it looks like self.query("R") is returning something unexpected. Maybe add a line above to print that value so you can see what's going on.

**Comment by ustunsoz** [comment]
I have already tried nothing comes up, printing only [102:]

**Comment by ductsoup** [comment]
At this point you might want to check with Atlas Scientific support.
